### PR TITLE
Run the TS code of the generated executable schema through Prettier

### PR DESCRIPTION
**Pull request by mandx**
This will respect the current project's formatting settings, as the destination filename will be used to resolve Prettier's configuration.

The Next.js example has `prettier` as a dependency and some minimal Prettier config, so the effect is observable.

Had to bump `pnpm` because of this bug https://github.com/pnpm/pnpm/issues/6424 (maybe you would like this in a separate PR?)

### CODE REVIEW

**Comment by captbaritone** [comment]
I wrote up my thoughts on how I was imagining Grats and code formatting working in this section of the docs: https://grats.capt.dev/docs/guides/workflows#managing-autoformatting-and-generated-files

I think I'd rather not tightly couple to Prettier, even via a peer dependency, when a more "Unix philosophy" approach of letting the user apply their own formatting seems nearly as good.

Curious to hear what you think of the suggestion I put in the docs. Is there a reason that feels unsatisfactory?

**Comment by mandx** [comment]
> Curious to hear what you think of the suggestion I put in the docs.

Well I totally missed that :sweat_smile: After reading that section and think about it some more, I now agree with you.

I don't like the format of the code TS generates (subjective opinion, of course) and adding this was fairly easy. However, just because we can, doesn't mean we should. Those who care about the `schema.ts`'s formatting can follow the instructions in the docs, as they are simple and straightforward to add to one's project. Also, while prettier is massively popular, it's not the only one, so this PR would kinda for it on others.

**Comment by mandx** [comment]
However the `pnpm` [bug is a real problem](https://github.com/pnpm/pnpm/issues/6424), and since it's a minor version bump, I believe a PR should be considered; what do you think?

**Comment by captbaritone** [comment]
I'm glad the docs were convincing! PR to upgrade pnpm version sounds good!

**Pull request closed without merging**
